### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#370]
- Update copyright ty be dynamic with JavaScript.
- Use Keiko Corp instead of Froala

**Comment by pritesh11-10** [comment]
I would like to claim this issue. Thanks.Please assign it to me

**Comment by Surya742** [comment]
I would like to work on this.

**Comment by trinhminhhieu** [comment]
I have completed your request. Please merge your pull request. Thanks!
add copyright .Update copyright ty be dynamic with JavaScript.Use Kei… #407

**Comment by brittneypostma** [comment]
@pritesh11-10  I am assigning this to @Surya742 since you already have another issue to work on.

**Comment by trinhminhhieu** [comment]
I have fixed the problem

**Comment by brittneypostma** [comment]
@trinhminhhieu it is in order of who claims it and who is assigned is given 24 hours. I will leave your pr open and merge it if @Surya742 doesn't fix it.
